version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install altair sphinx-rtd-theme==3.0.0rc3
      - pip install .

sphinx:
  configuration: docs/conf.py
