version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install altair sphinx-rtd-theme tomli sphinxcontrib-napoleon poetry
      - pip install .[pyqt5,pyqt6,panel]
sphinx:
  configuration: docs/conf.py
