version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install altair sphinx-rtd-theme==3.0.0rc3 tomli sphinxcontrib-napoleon
      - pip install .
    pre_build:
     - SPHINX_APIDOC_OPTIONS=members,show-inheritance sphinx-apidoc -o docs/source src
sphinx:
  configuration: docs/conf.py
